[Variables]
Layout=horizontal.inc
LoadMeter={'background_meter.inc','icon_meter.inc'}
SkinWidth=0.9
SkinX=0.04
SkinY=0.12
List=list_game.inc
Space=25
RowSpace=0
Rows=1
ScrollSpeed=0.1
ScrollDivider=8
Transition=5
IconSolid=0,0,0,150
IconTint=255,255,255
IconScale=0.4
BannerWidth=314.18
BannerHeight=576
Update=20
ClickThrough=0
CoverAspectRatio=0
StaticBackground=1
Keyboard=1
Gamepad=1
LaunchAction=[!CommandMeasure Animation "launch_effect()"]
SoundHover=hover_1.wav
SoundClick=launch.wav
SoundExit=exit.wav


