[Variables]

Language=English
Location=SPXX0050
Unit=m

FontColor=0,0,0
FontFace=Futura Lt

Player=Winamp                   

;-------------------------------------------------------------
;-------------------------------------------------------------

;Meny panel settings
;Enter your settings here:

Text1=- Photoshop
Text2=Google
Text3=Youtube
Text4=Gmail
Text5=Facebook
Text6=Deviantart -

Path1=C:\Program Files\Adobe\Adobe Photoshop CC 2015 (32 Bit)\Photoshop.exe
Path2=https://google.com
Path3=https://youtube.com
Path4=https://www.gmail.com
Path5=https://facebook.com
Path6=https://www.deviantart.com/browse/all/customization/skins/sysmonitor/rainmeter/?order=5

;-------------------------------------------------------------
;-------------------------------------------------------------

;Visualiser settings
;Please dont eddit these settings if you don't know what you doing

FFTSize=2048
FFTOverlap=1024
FFTAttack=650
FFTDecay=250
FreqMin=100
FreqMax=16000
Sensitivity=35
PlayerSwitch=0
