chcp 857

@echo off

set gamesfol1="Tarayçcç oyunlarç"
set gamesfol2="Seferberlik"
set gamesfol3="GÅndelik"
set gamesfol4="Mini oyun"
set gamesfol5="Äevrimdçüç áok oyunculu"
set gamesfol6="Äevrimiái áok oyunculu"
set gamesfol7="SimÅlasyon"
set gamesfol8="Spor & yarçü"
set gamesfol9="Sanal Geráeklik"
set gamescamfol1="Aksiyon"
set gamescamfol2="Korku"
set gamescamfol3="Sakin"
set gamescamfol4="RPG"
set gamescamfol5="Hayatta kalma"
set gameslocfol1="Eüli oyun"
set gameslocfol2="Partili"
set gameslocfol3="Karüçlçklç vs"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Niüan"
set gamesonlfol4="Strateji"

set newsmediafol1="Aüçrç-sola"
set newsmediafol2="Aüçrç-saßa"
set newsmediafol3="Uluslararasç"

set onlinetools1fol="Tanç"

set podcastsfol1="Suá & drama"
set podcastsfol2="Past & Present"
set podcastsfol3="Siyaset"
set podcastsfol4="Biliüim & Teknoloji"
set podcastsfol5="Sex & Psikoloji"
set podcastsfol6="Spor"
set podcastsfol7="Talk show"

set bookmarksfol1="Haberler & medya"
set bookmarksfol2="Äevrimiái araálar"
set bookmarksfol3="Ortam akçüç"
set bookmarksfol4="Alçüveriüler"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Disney+"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Komut satçrç"
set advanced2="Aygçt yîneticisi"
set advanced3="Disk temizleme"
set advanced4="Disk yînetimi"
set advanced5="Kayçt defteri dÅzenl."
set advanced6="Kaynak izleyicisi"
set advanced7="Baülangçá Uygulamalarç"
set advanced8="Depolama alanlarç"
set advanced9="Sistem yapçlandçrmasç"
set advanced10="Windows gÅvenlik duvarç"
set advanced11="Windows PowerShell"
set advanced12="Windows hizmetleri"

set controlfol1="Geliümiü Kontroller"
set control1="MasaÅstÅ arkaplanç"
set control2="GîrÅntÅ ayarlarç"
set control3="BÅyÅteá"
set control4="Ekran klavyesi"
set control5="GÅá seáenekleri"
set control6="Geri dînÅüÅm kutusu"
set control7="Ekranç deßiütir"
set control8="Sistem bilgileri"
set control9="Gîrev yîneticisi"
set control10="Program kaldçr"
set control11="Kullançcç hesaplarç"

cd %~dp0

call "RenameShortcuts.bat"