[0]
Meter=String
MeterStyle=s
Text=256
LeftMouseDownAction=[!SetVariable FFTSize "256" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables FFTSize "256" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption FFTSize_Select Text "256" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[1]
Meter=String
MeterStyle=s
Text=512
LeftMouseDownAction=[!SetVariable FFTSize "512" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables FFTSize "512" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption FFTSize_Select Text "512" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[2]
Meter=String
MeterStyle=s
Text=1024
LeftMouseDownAction=[!SetVariable FFTSize "1024" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables FFTSize "1024" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption FFTSize_Select Text "1024" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[3]
Meter=String
MeterStyle=s
Text=2048
LeftMouseDownAction=[!SetVariable FFTSize "2048" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables FFTSize "2048" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption FFTSize_Select Text "2048" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[4]
Meter=String
MeterStyle=s
Text=3072
LeftMouseDownAction=[!SetVariable FFTSize "3072" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables FFTSize "3072" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption FFTSize_Select Text "3072" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[5]
Meter=String
MeterStyle=s
Text=4096
LeftMouseDownAction=[!SetVariable FFTSize "4096" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables FFTSize "4096" "D:\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption FFTSize_Select Text "4096" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
