[Rainmeter]

[Variables]

[DisabledApp]
ImageAlpha=75
FontColor=#DropdownFontColor1#,75
MouseOverAction=[!UpdateMeter FolderBlock][!Redraw]
MouseLeaveAction=[]
FillColor=Fill Color #DropdownFontColor1#,75

;---

[1]
MeterStyle=InfoStyle | DisabledApp

[1Icon]
MeterStyle=IconStyle | DisabledApp

[1Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[2]
MeterStyle=InfoStyle | DisabledApp

[2Icon]
MeterStyle=IconStyle | DisabledApp

[2Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[3]
MeterStyle=InfoStyle | DisabledApp

[3Icon]
MeterStyle=IconStyle | DisabledApp

[3Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[4]
MeterStyle=InfoStyle | DisabledApp

[4Icon]
MeterStyle=IconStyle | DisabledApp

[4Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[7]
MeterStyle=InfoStyle | DisabledApp

[7Icon]
MeterStyle=IconStyle | DisabledApp

[7Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[15]
MeterStyle=InfoStyle | DisabledApp

[15Icon]
MeterStyle=IconStyle | DisabledApp

[15Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[17]
MeterStyle=InfoStyle | DisabledApp
Hidden=1

[17Icon]
MeterStyle=IconStyle | DisabledApp
ImageName=
Hidden=1

[17Arrow]
MeterStyle=ArrowStyle | DisabledApp
Hidden=1

;---

[18]
MeterStyle=InfoStyle | DisabledApp
Hidden=1

[18Icon]
MeterStyle=IconStyle | DisabledApp
ImageName=
Hidden=1

[18Arrow]
MeterStyle=ArrowStyle | DisabledApp
Hidden=1

;---

[19]
MeterStyle=InfoStyle | DisabledApp
Hidden=1

[19Icon]
MeterStyle=IconStyle | DisabledApp
ImageName=
Hidden=1

[19Arrow]
MeterStyle=ArrowStyle | DisabledApp
Hidden=1

;---

[20]
MeterStyle=InfoStyle | DisabledApp
Hidden=1

[20Icon]
MeterStyle=IconStyle | DisabledApp
ImageName=
Hidden=1

[20Arrow]
MeterStyle=ArrowStyle | DisabledApp
Hidden=1

;---

[21]
MeterStyle=InfoStyle | DisabledApp
Hidden=1

[21Icon]
MeterStyle=IconStyle | DisabledApp
ImageName=
Hidden=1

[21Arrow]
MeterStyle=ArrowStyle | DisabledApp
Hidden=1

;---

[22]
MeterStyle=InfoStyle | DisabledApp
Hidden=1

[22Icon]
MeterStyle=IconStyle | DisabledApp
ImageName=
Hidden=1

[22Arrow]
MeterStyle=ArrowStyle | DisabledApp
Hidden=1