@echo Reseting configurations to default
"C:\Program Files\Rainmeter\Rainmeter.exe" !DeactivateConfigGroup DroptopSuite
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 0 %1Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !CommandMeasure MeasureRun "Run"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc1 "#SKINSPATH#Droptop Folders\PinnedApps" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc2 "#SKINSPATH#Droptop Folders\Games" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc3 "#SKINSPATH#Droptop Folders\Bookmarks" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc4 "#SKINSPATH#Droptop Folders\Control" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc6 "#SKINSPATH#Droptop Folders\CustomFolder1" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc7 "#SKINSPATH#Droptop Folders\CustomFolder2" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc8 "#SKINSPATH#Droptop Folders\CustomFolder3" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc9 "#SKINSPATH#Droptop Folders\CustomFolder4" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc10 "#SKINSPATH#Droptop Folders\CustomFolder5" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc11 "#SKINSPATH#Droptop Folders\CustomFolder6" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderLoc12 "#SKINSPATH#Droptop Folders\CustomFolder7" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID1 "JaxCore" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID2 "Quick_Settings-Cariboudjan" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID3 "Recycle_Bin-Phanlock" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID4 "Daily_Quotes-Bunz" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomAppID5 "Sample_App-Cariboudjan" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables JaxCore 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Quick_Settings-Cariboudjan 2 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Recycle_Bin-Phanlock 3 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Daily_Quotes-Bunz 4 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Sample_App-Cariboudjan 5 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ReverseDarkLight 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables RecentFileFilter "" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables GmailUsername "Unassigned" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables GmailPassword "Password" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmHour 9 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmMinute 30 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmNum 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlarmOFF 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarHideGradient 1 %1Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarOpacity1 150 %1Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarGradientOpacity1 75 %1Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DropdownMenuOpacity1 200 %1Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SetColorByWallpaperOFF 0 %1Droptop\@Resources\Themes\1Settings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideSupport 0 %1Droptop\Other\Settings\Settings.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UnitsMetric 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideIcons 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideSubIcons 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeColumn 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeRow 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables CustomHomeButton 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HomeColorNum 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailNum 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink1 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor1 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject1 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink2 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor2 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject2 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink3 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor3 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject3 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailLink4 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailAuthor4 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MailSubject4 """""" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MonitorNum "" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables UpdateAvailable 0 %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AppCommandCount 1 %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 0 %1Droptop\Other\Welcome\Start.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NoAnimationNum 0 %1Droptop\Other\Welcome\Style.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DroptopSize 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconSize Small %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopIconSize Medium %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopIconWH 32 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconW 16 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IconH 16 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIOverride 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DPIRescaleOFF 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AutohideSpeedNum 2 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !KeepOnScreenGroup 1 "Folder0"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ExchangeNum 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ExchangeLastUpdated N/A %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables String1 "Custom 1" %1Droptop\@Resources\Symbols\Symbols11.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables String2 "Custom 2" %1Droptop\@Resources\Symbols\Symbols11.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables String3 "Custom 3" %1Droptop\@Resources\Symbols\Symbols11.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables String4 "Custom 4" %1Droptop\@Resources\Symbols\Symbols11.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables String5 "Custom 5" %1Droptop\@Resources\Symbols\Symbols11.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AutoMuteON 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerNum 6 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTypeNum 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle0 "-" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist0 "-" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle1 "-" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist1 "-" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerTitle2 "-" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PlayerArtist2 "-" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables WebNowPlayingAlbumImage "" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AlwaysShowSongTitleOFF 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideTimeCenter 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LanguageNum 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ThemeNum 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Time24HourNum 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Xnum 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Ynum 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Xpos 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Ypos 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables StretchNum 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables IPAddress "N/A" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TooltipDismissed 0 %1Droptop\Other\SystemTray\Volume\Volume.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder1 1 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder2 2 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder3 3 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder4 4 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder5 5 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder6 6 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder7 7 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder8 8 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder9 9 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder10 10 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder11 11 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SlotFolder12 12 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName1 #SysName1# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName2 #SysName2# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName3 #SysName3# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName4 #SysName4# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName5 #SysName5# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName6 #SysName6# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName7 #SysName7# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName8 #SysName8# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName9 #SysName9# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName10 #SysName10# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName11 #SysName11# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName12 #SysName12# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName13 #SysName13# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName14 #SysName14# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName15 #SysName15# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName16 #SysName16# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName17 #SysName17# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName18 #SysName18# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName19 #SysName19# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName20 #SysName20# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName21 #SysName21# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlotName22 #SysName22# %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot1 1 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot2 2 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot3 3 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot4 4 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot5 5 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot6 6 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot7 7 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot8 8 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot9 9 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot10 10 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot11 11 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot12 12 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot13 13 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot14 14 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot15 15 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot16 16 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot17 17 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot18 18 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot19 19 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot20 20 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot21 21 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysSlot22 22 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosNewDesktop 1 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosAction 2 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosLanguage 3 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosAssistant 4 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosSearch 5 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosTime 6 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosAlarm 7 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosVolume 8 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosMail 9 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosWeather 10 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosBattery 11 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosWifi 12 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosDownloads 13 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosRecent 14 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosCopy 15 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosExchange 16 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosCustomApp1 17 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosCustomApp2 18 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosCustomApp3 19 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosCustomApp4 20 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosCustomApp5 21 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SysPosAppDrawer 22 %1Droptop\@Resources\GlobalVar\TopBarPos.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden1 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden2 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden3 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden4 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden5 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden6 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden7 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden8 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden9 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden10 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden11 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderHidden12 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppNewDesktop 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAction 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppSearch 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppTime 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppMail 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAlarm 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppVolume 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppWeather 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppWifi 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppBattery 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppDownloads 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppRecent 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCopy 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppExchange 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppLanguage 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAppDrawer 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppAssistant 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp1 0 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp2 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp3 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp4 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideAppCustomApp5 1 %1Droptop\@Resources\GlobalVar\FolderSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideProgramsApp 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideMailCount 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables HideGmailPreviews 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables AHKNum 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables SearchModeNum 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ExchangeCurrency1 "EUR" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ExchangeCurrency2 "CNY" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables DebugModeOFF 1 %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables TopBarWidth "#WORKAREAWIDTH#" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LocationLatitude "" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LocationLongitude "" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables MyLocation "" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NumberOfItems 1 %1Droptop\Other\SystemTray\Downloads\Downloads.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables NumberOfItems 1 %1Droptop\Other\SystemTray\Recent\Recent.ini"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables EnableDragDrop 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ZposBehavior 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables PopupInFullscreen 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note1 "#NotesItem1#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note2 "#NotesItem2#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note3 "#NotesItem3#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note4 "#NotesItem4#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Note5 "#NotesItem5#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle1 "#FolderName1#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle2 "#FolderName2#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle3 "#FolderName3#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle4 "#FolderName4#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle5 "#FolderName5#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle6 "#FolderName6#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle7 "#FolderName7#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle8 "#FolderName8#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle9 "#FolderName9#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle10 "#FolderName10#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle11 "#FolderName11#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FolderTitle12 "#FolderName12#" %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedApp "Explorer" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedIM "Explorer.EXE" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables LastFocusedTitle "" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ProcessPath "C:\WINDOWS\Explorer.EXE" %1Droptop\@Resources\GlobalVar\Control.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables ProcessLoc "C:\WINDOWS\" %1Droptop\@Resources\GlobalVar\Control.inc"
call %1Droptop\@Resources\Scripts\LanguageScripts\RestoreFolders.bat" %1
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "#PROGRAMPATH#Rainmeter.exe" /t "REG_SZ" /d "" /f
@echo Creating distributables - All versions
TIMEOUT 10
del /f /q %1Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Apps\*"
del /f /q %1Droptop\@Resources\Scripts\AppBuilder\@Rmskins\Droptop Themes\*"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 0 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop Community Apps"
xcopy /E /I /Y %1Droptop Community Apps" %1Redistributables\Basic-Version\Skins\Droptop Community Apps" /EXCLUDE:XcopyExclude.txt
xcopy /E /I /Y %1Droptop" %1Redistributables\Basic-Version\Skins\Droptop"
xcopy /E /I /Y %1Droptop\@Resources\OriginalFolders" %1Redistributables\Basic-Version\Skins\Droptop Folders"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder12"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder11"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder10"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder9"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder8"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\Other\Folders\Folder7"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column1"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column2"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column3"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column4"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column5"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column6"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column7"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column8"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column9"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column10"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column11"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column12"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column13"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column14"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column15"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column16"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column17"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column18"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\16\Column19"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column1"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column2"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column3"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column4"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column5"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column6"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column7"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column8"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column9"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column10"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column11"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column12"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column13"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column14"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column15"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column16"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column17"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column18"
RD /S /Q %1Redistributables\Basic-Version\Skins\Droptop\@Resources\TopImages\Home\32\Column19"
@echo Basic Version Complete
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 1 %1Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 99 %1Droptop\Other\Welcome\Start.ini"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop Community Apps"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop Folders"
xcopy /E /I /Y %1Droptop" %1Redistributables\Supporter-Version\Skins\Droptop"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Icons"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\OriginalFolders"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder01"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder02"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder1"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder2"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder3"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder4"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder5"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Folders\Folder6"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\ApplicationMenu"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\DialogMenu"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\DropdownBar"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Folders"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\PowerMenu"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\SettingsMenu"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Misc"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\SystemTray"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\Tutorial"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Addons"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Dialog"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Extras"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\FileTypeIcons"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Fonts"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Images"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\LuaScripts"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\MediaImages"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Meters"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\PresetIcons"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Scripts"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\SetupImages"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Sounds"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Symbols"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\ThemeImages"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\FixedIcons"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Calendars"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Alarm"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Battery"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Copy"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Downloads"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Exchange"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Layer"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Mail"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Misc"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Notes"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Recent"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Search"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Time"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Volume"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Weather"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Wifi"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Action"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Desktops"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Language"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\AppDrawer"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\TopImages\Assistant"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Weather"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Languages"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\Other\BackgroundProcesses"
RD /S /Q %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\Themes"
del /f %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\Control.inc"
del /f %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\IncludedCommands.inc"
del /f %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\FolderSettings.inc"
del /f %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\TopBarPos.inc"
del /f %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\UserSettings.inc"
del /f %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\CustomAppSettings.inc"
del /f %1Redistributables\Supporter-Version\Skins\Droptop\@Resources\GlobalVar\SettingsMenuOptions.inc"
@echo Supporter Version Complete
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables FirstLoad 1 %1Droptop\@Resources\GlobalVar\UserSettings.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Supporter 0 %1Droptop\@Resources\GlobalVar\Supporter.inc"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 100 %1Droptop\Other\Welcome\Start.ini"
RD /S /Q %1Redistributables\Update\Skins\Droptop"
xcopy /E /I /Y %1Droptop" %1Redistributables\Update\Skins\Droptop"
taskkill /f /im "Droptop Rainmeter.exe"
powershell.exe cd %1Redistributables"; Remove-Item '.\@Rmskins\Basic-Version\*.zip'; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Remove-Item '.\@Rmskins\Basic-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Update\*.rmskin' -Recurse; Remove-Item '.\@Rmskins\Beta-Update\*.rmskin' -Recurse; .\MakeRmSkin.ps1 -Skin Basic-Version; .\MakeRmSkin.ps1 -Skin Supporter-Version; .\MakeRmSkin.ps1 -Skin Update; Remove-Item '.\@Rmskins\Basic-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Supporter-Version\*.zip' -Recurse; Remove-Item '.\@Rmskins\Update\*.zip' -Recurse; Rename-Item -Path '.\@Rmskins\Basic-Version\Basic-Version.rmskin' -NewName 'Droptop Basic Version.rmskin'; Rename-Item -Path '.\@Rmskins\Supporter-Version\Supporter-Version.rmskin' -NewName 'Droptop Supporter Version.rmskin'; Rename-Item -Path '.\@Rmskins\Update\Update.rmskin' -NewName 'Droptop Update.rmskin'; Copy-Item '.\@Rmskins\Update\Droptop Update.rmskin' -Destination '.\@Rmskins\Beta-Update'; Rename-Item -Path '.\@Rmskins\Beta-Update\Droptop Update.rmskin' -NewName 'Droptop Beta Update.rmskin'
xcopy /E /I /Y %1Redistributables\@Rmskins\Basic-Version\*" "%USERPROFILE%\Documents\GitHub\Basic-Version\"
xcopy /E /I /Y %1Redistributables\@Rmskins\Supporter-Version\*" "%USERPROFILE%\Documents\GitHub\Supporter-Version\"
xcopy /E /I /Y %1Redistributables\@Rmskins\Beta-Update\*" "%USERPROFILE%\Documents\GitHub\Beta-Update\"
xcopy /E /I /Y %1Redistributables\@Rmskins\Update\*" "%USERPROFILE%\Documents\GitHub\Update\"
"C:\Users\thomas.whittaker\AppData\Local\GitHubDesktop\GitHubDesktop.exe"
"C:\Program Files\Rainmeter\Rainmeter.exe" !WriteKeyValue Variables Page 0 %1Droptop\Other\Welcome\Start.ini"
powershell.exe [console]::beep(500,100); [console]::beep(1200,120)
@echo All distributables finished successfully. Press any key to launch setup.
PAUSE
"C:\Program Files\Rainmeter\Rainmeter.exe" !ActivateConfig "Droptop\Other\Welcome" "Start.ini"